- name: Install supervisor-{{ version }} by {{ pip_exe }}.
  pip:
    name: supervisor
    version: "{{ version }}"
    executable: "{{ pip_exe }}"
    state: present
    extra_args: --index-url={{ pip_index_url }}


- name: Link to /usr/local/bin/supervisorctl
  file:
    src: "{{ supervisorctl_exe }}"
    dest: /usr/local/bin/supervisorctl
    state: link
    force: yes


- name: Link to /usr/local/bin/supervisord
  file:
    src: "{{ supervisord_exe }}"
    dest: /usr/local/bin/supervisord
    state: link
    force: yes


- name: Initializing config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
  loop:
    - "/etc/supervisord"
    - "/etc/supervisord.d"
    - "/etc/supervisor.d"