---
# tasks file for supervisor
- name: Check status of supervisor-{{ version }}.
  stat:
    path: "/usr/local/bin/supervisord"
  register: supervisor

# - debug: var=supervisorctl.stat

- include: install-supervisor.yml
  static: no
  when: supervisor.stat.exists == False or supervisor.stat.executable == False

- name: Already exists supervisor-{{ version }}.
  debug: msg="Already exists a supervisor in '/usr/local/bin/supervisord'"
  when: supervisor.stat.exists == True and supervisor.stat.executable == True

- service: name=supervisord enabled=yes state=started
