---
# tasks file for supervisor
- name: Check status of supervisor-{{ version }}.
  stat:
    path: "/usr/local/bin/supervisord"
  register: supervisor

# - debug: var=supervisorctl.stat

- include: install-supervisor.yml
  static: no
  when: not supervisor.stat.exists or not supervisor.stat.executable

- name: Already exists supervisor-{{ version }}.
  debug: msg="Already exists a supervisor in '/usr/local/bin/supervisord'"
  when: supervisor.stat.exists and supervisor.stat.executable

- name: Starting supervisor-{{ version }}.
  service: name=supervisord enabled=yes state=started
